pipeline {
    agent any

    environment {
        GCP_PROJECT = 'devops-school-enuygun'
        GCR_CREDENTIALS = credentials('gcr-json-key')
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/mete20/end-to-end-devops.git'
            }
        }
        stage('Build Docker Images') {
            steps {
                script {
                    def services = ['service1', 'service2']
                    for (service in services) {
                        sh "docker build -t yakametehan/end-to-end/${service}:latest -f ./microservices/${service}/Dockerfile.${service} ./microservices/${service}"                    }
                }
            }
        }
        stage('Push Docker Images') {
            steps {
                script {
                    def services = ['service1', 'service2']
                    for (service in services) {
                        sh "docker push yakametehan/end-to-end/${service}:latest"
                    }
                }
            }
        }
        stage('Deploy to GKE') {
            steps {
                withCredentials([file(credentialsId: 'gcr-json-key', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                    sh "helm upgrade --install my-app ./helm-chart --set image.repository=yakametehan/end-to-end/"
                }
            }
        }
    }
}
